oil/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/admin', function () {
    //echo(567894589);
    return view('layouts.admin');
})->name('admin');


Route::get('/admin/general', [App\Http\Controllers\GeneralController::class, 'index'])->name('admin.generals.index');
Route::get('/admin/general/edit', [App\Http\Controllers\GeneralController::class, 'edit'])->name('admin.generals.edit');
Route::patch('/admin/general/update', [App\Http\Controllers\GeneralController::class, 'update'])->name('admin.generals.update');


Route::get('/admin/sliders', [App\Http\Controllers\SliderController::class, 'index'])->name('admin.sliders.index');
Route::get('/admin/sliders/create', [App\Http\Controllers\SliderController::class, 'create'])->name('admin.sliders.create');
Route::post('/admin/sliders', [App\Http\Controllers\SliderController::class, 'store'])->name('admin.sliders.store');
Route::get('/admin/sliders/{slider}/edit', [App\Http\Controllers\SliderController::class, 'edit'])->name('admin.sliders.edit');
Route::patch('/admin/sliders/{slider}/update', [App\Http\Controllers\SliderController::class, 'update'])->name('admin.sliders.update');
Route::delete('/admin/sliders/{slider}/destroy', [App\Http\Controllers\SliderController::class, 'destroy'])->name('admin.sliders.destroy');


Route::get('/admin/users', [App\Http\Controllers\UserController::class, 'index'])->name('admin.users.index');
Route::get('/admin/users/create', [App\Http\Controllers\UserController::class, 'create'])->name('admin.users.create');
Route::post('/admin/users', [App\Http\Controllers\UserController::class, 'store'])->name('admin.users.store');
Route::get('/admin/users/{user}/edit', [App\Http\Controllers\UserController::class, 'edit'])->name('admin.users.edit');
Route::patch('/admin/users/{user}/update', [App\Http\Controllers\UserController::class, 'update'])->name('admin.users.update');
Route::delete('/admin/users/{user}/destroy', [App\Http\Controllers\UserController::class, 'destroy'])->name('admin.users.destroy');



Route::get('/', function () {
    
    return view('index',['sliders'=>\App\Models\Slider::all(),'general'=>\App\Models\General::findOrFail(1)]);
})->name('index');


Route::get('/about', function () {
    return view('about',[]);
})->name('about');

Route::get('/services', function () {
    return view('services');
})->name('services');

Route::get('/suppliers', function () {
    return view('suppliers');
})->name('suppliers');

Route::get('/contact', function () {
    return view('contact');
})->name('contact');

oil/app/Models/slider.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class slider extends Model
{
    use HasFactory;
    protected $guarded=[];


    public function getImageAttribute($value) {
        if (strpos($value, 'https://') !== FALSE || strpos($value, 'http://') !== FALSE) {
            return $value;
        }
        if($value===null)
        {
            return null;
        }
        return asset('storage/images/sliders/' . $value);
    }

}

oil/resources/views/admin/controlpage.blade.php
@extends('layouts.admin')
@section('content')
<div class="container-fluid">


     <div style="overflow-x:auto;">
          <div class="card-body">
               <form action="{{ route('admin.users.store') }}" method="POST">
                    @csrf
          
          
                    <div class="form-group">
               
                         <label for="name"> Country :</label>
                         <input type="text" name="country" class="form-control" id="" aria-description=""  value="{{ old('country') }}" placeholder="">
                         @error('country')
                              <div class="alert alert-danger">{{ $message }}</div>
                         @enderror
                    </div>

                    <div class="form-group">
               
                         <label for="name"> City :</label>
                         <input type="text" name="City" class="form-control" id="" aria-description=""  value="{{ old('City') }}" placeholder="">
                         @error('City')
                              <div class="alert alert-danger">{{ $message }}</div>
                         @enderror
                    </div>

                    <div class="form-group">
               
                         <label for="name"> Start WorkDays :</label>
                         <input type="text" name="City" class="form-control" id="" aria-description=""  value="{{ old('City') }}" placeholder="">
                         @error('City')
                              <div class="alert alert-danger">{{ $message }}</div>
                         @enderror
                    </div>

                    <div class="form-group">
               
                         <label for="name"> End WorkDays :</label>
                         <input type="text" name="City" class="form-control" id="" aria-description=""  value="{{ old('City') }}" placeholder="">
                         @error('City')
                              <div class="alert alert-danger">{{ $message }}</div>
                         @enderror
                    </div>

                    <div class="form-group">
               
                         <label for="name"> Start WorkTimes :</label>
                         <input type="text" name="City" class="form-control" id="" aria-description=""  value="{{ old('City') }}" placeholder="">
                         @error('City')
                              <div class="alert alert-danger">{{ $message }}</div>
                         @enderror
                    </div>

                    <div class="form-group">
               
                         <label for="name"> End WorkTimes :</label>
                         <input type="text" name="City" class="form-control" id="" aria-description=""  value="{{ old('City') }}" placeholder="">
                         @error('City')
                              <div class="alert alert-danger">{{ $message }}</div>
                         @enderror
                    </div>
                    <div class="form-group">
               
                         <label for="email">  E-mail :</label>
                         <input type="email" name="email" class="form-control" id="" aria-description=""   value="{{ old('email') }}" placeholder=" ">
                         @error('email')
                              <div class="alert alert-danger">{{ $message }}</div>
                         @enderror
                    </div>


                    <div class="form-group">
               
                         <label for="password">  Sliders : </label>
                         @foreach ($sliders as $slider)
                              <img src="{{$slider->image}}" alt="">
                              <h3>{{$slider->title}}</h3>
                              <h3>{{$slider->description}}</h3>
                         @endforeach
                         <input type="password" name="password" class="form-control" id="" aria-description="" placeholder="">
                         @error('password')
                              <div class="alert alert-danger">{{ $message }}</div>
                         @enderror
                    </div>

                    <div id="InputEmails" class="form-group">
                         <label for="Emails">Sliders: </label>
                         @foreach ($sliders as $slider)
                              <input type="text" class="form-control form-control-edit" name="title[]"  value={{$slider->title}} ><br>
                              <input type="text" class="form-control form-control-edit" name="description[]"  value={{$slider->description}} ><br>
                              <input type="file" class="form-control form-control-edit" name="images[]"  value={{$item}} ><br>
                              <img src="{{$slider->image}}" alt="">

                         @endforeach
                    </div>
                    <a id="add-email" class="btn btn-info" style="width: 30%;direction:rtl;"> Add new slider </a>



                    <div class="form-group">
               
                         <label for="password_confirmation"> Password Confirmation : </label>
                         <input type="password" name="password_confirmation" class="form-control" id="" aria-description="" placeholder="">
                         @if (Session::has('user-password-message'))
                         <div class="alert alert-danger">
                         
                           {{Session::get('user-password-message')}}
                         </div> 
                         @endif
          
                    </div>
                   {{-- <div class="form-group">
               
                    <label for="file">صورة المستخدم</label>
                    <input type="file" name="image" class="form-control-file"  placeholder="">
                    @error('image')
                         <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div> --}}
                   <button type="submit" class="btn btn-primary btn-block">Submit</button>
               
               </form>
          </div>  
     </div>
</div>
@endsection

oil/resources/views/admin/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="container-fluid">
     <h2>Sidebar Dropdown</h2>

     <div style="overflow-x:auto;">
          <table>
               <tr>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Points</th>

               </tr>
               <tr>
                    <td>Jill</td>
                    <td>Smith</td>
                    <td>50</td>

               </tr>
               <tr>
                    <td>Eve</td>
                    <td>Jackson</td>
                    <td>94</td>

               </tr>
               <tr>
                    <td>Adam</td>
                    <td>Johnson</td>
               </tr>
          </table>
     </div>
</div>
@endsection