oil/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/admin', function () {
    //echo(567894589);
    return view('layouts.admin');
})->name('admin');


Route::get('/admin/general', [App\Http\Controllers\GeneralController::class, 'index'])->name('admin.generals.index');
Route::get('/admin/general/edit', [App\Http\Controllers\GeneralController::class, 'edit'])->name('admin.generals.edit');
Route::patch('/admin/general/update', [App\Http\Controllers\GeneralController::class, 'update'])->name('admin.generals.update');


Route::get('/admin/sliders', [App\Http\Controllers\SliderController::class, 'index'])->name('admin.sliders.index');
Route::get('/admin/sliders/create', [App\Http\Controllers\SliderController::class, 'create'])->name('admin.sliders.create');
Route::post('/admin/sliders', [App\Http\Controllers\SliderController::class, 'store'])->name('admin.sliders.store');
Route::get('/admin/sliders/{slider}/edit', [App\Http\Controllers\SliderController::class, 'edit'])->name('admin.sliders.edit');
Route::patch('/admin/sliders/{slider}/update', [App\Http\Controllers\SliderController::class, 'update'])->name('admin.sliders.update');
Route::delete('/admin/sliders/{slider}/destroy', [App\Http\Controllers\SliderController::class, 'destroy'])->name('admin.sliders.destroy');


Route::get('/admin/users', [App\Http\Controllers\UserController::class, 'index'])->name('admin.users.index');
Route::get('/admin/users/create', [App\Http\Controllers\UserController::class, 'create'])->name('admin.users.create');
Route::post('/admin/users', [App\Http\Controllers\UserController::class, 'store'])->name('admin.users.store');
Route::get('/admin/users/{user}/edit', [App\Http\Controllers\UserController::class, 'edit'])->name('admin.users.edit');
Route::patch('/admin/users/{user}/update', [App\Http\Controllers\UserController::class, 'update'])->name('admin.users.update');
Route::delete('/admin/users/{user}/destroy', [App\Http\Controllers\UserController::class, 'destroy'])->name('admin.users.destroy');



Route::get('/', function () {
    
    return view('index',['sliders'=>\App\Models\Slider::all(),'general'=>\App\Models\General::findOrFail(1)]);
})->name('index');


Route::get('/about', function () {
    return view('about',[]);
})->name('about');

Route::get('/services', function () {
    return view('services');
})->name('services');

Route::get('/suppliers', function () {
    return view('suppliers');
})->name('suppliers');

Route::get('/contact', function () {
    return view('contact');
})->name('contact');

oil/app/Models/general.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class general extends Model
{
    use HasFactory;
    protected $guarded=[];
    protected $casts=[
        'supplies'=>'array',
        'services'=>'array',
        //'link'=>'array'
    ];

    

    public function getLogoAttribute($value) {
        if (strpos($value, 'https://') !== FALSE || strpos($value, 'http://') !== FALSE) {
            return $value;
        }
        if($value===null)
        {
            return null;
        }
        return asset('storage/images/generals/' . $value);
    }

}

oil/resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>دليل الشركات</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <style>
        .card {
    border: 2px solid #95ccf9;
    position: relative;
    display: flex;
    flex-direction: column;
    min-width: 0;
    word-wrap: break-word;
    background-color: #fff;
    background-clip: border-box;
    /* border: 1px solid rgba(0, 0, 0, 0.125); */
    border-radius: 0.25rem;
}
.card-header:first-child {
    color: #1362a2;
    font-size: 27px;
    padding-top: 2px;
    padding-bottom: 2px;
    font-weight: bold;
    border-bottom: 2px solid #95ccf9;
    border-radius: calc(0.25rem - 1px) calc(0.25rem - 1px) 0 0;
}
.form-control{
        border: 2px solid #95ccf9;
        background-color: #fff;
    }
    .col-form-label {
    color: #166cb6;
    padding-top: calc(0.375rem + 1px);
    padding-bottom: calc(0.375rem + 1px);
    margin-bottom: 0;
    font-size: inherit;
    line-height: 1.6;
}
    </style>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            {{-- <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif
                            
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @endguest
                    </ul>
                </div>
            </div> --}}
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

oil/resources/views/layouts/base.blade.php
<!doctype html>
<html class="no-js" lang="zxx">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>Oilfield Support</title>
        <meta name="description" content="UrbanHouse is a business HTML5 template for construction, building companies and those that offer building services. This template is the perfect solution for you because is a clean and modern template and contain 9 HTML files. All the files are easy to edit and well Documented.">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Place favicon.ico in the root directory -->
        <link rel="shortcut icon" type="image/ico" href={{asset("assets/images/favicon.ico")}}/>
        <!-- Fonts css -->
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
        <!-- Bootstrap 4 Beta CSS -->
        <link rel="stylesheet" href={{asset("assets/css/bootstrap.min.css")}}>
        <!-- Animate CSS -->
        <link rel="stylesheet" href={{asset("assets/css/animate.css")}}>
        <!-- Owl Carousel CSS -->
        <link rel="stylesheet" href={{asset("assets/css/owl.carousel.min.css")}}>
        <!-- Owl Carousel Theme default CSS -->
        <link rel="stylesheet" href={{asset("assets/css/owl.theme.default.min.css")}}>
        <!-- Font Awesome 4.7.0 CSS -->
        <link rel="stylesheet" href={{asset("assets/css/font-awesome.min.css")}}>
        <!-- Magnific Popup CSS -->
        <link rel="stylesheet" href={{asset("assets/css/magnific-popup.css")}}>
        <!-- Main CSS -->
        <link rel="stylesheet" href={{asset("assets/css/style.css")}}>
    </head>
    <body>
        <!-- START Header -->
        <header>
            <!-- START Header Top Contact Area -->
            <div class="header-top-area">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-md-6">
                            <ul class="header-info-left">
                                <li><span><i class="fa fa-map-marker" aria-hidden="true"></i> </span>{{$general->country}} / {{$general->city}}.</li>
                                <li><span><i class="fa fa-phone" aria-hidden="true"></i> </span>+90 534 078 13 62</li>
                                <li><span><i class="fa fa-clock-o" aria-hidden="true"></i> </span>{{$general->startworkdays}} - {{$general->endworkdays}}: {{$general->startworktimes}} - {{$general->endworktimes}}</li>
                            </ul>
                        </div>
                        <div class="col-md-6">
                            <ul class="header-info-right">
                                <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                                <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                                <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
<!--                                <li><a href="#"><i class="fa fa-calculator" aria-hidden="true"></i> Cost Calculator</a></li>-->
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- END Header Top Contact Area -->
            <!-- START Header Menu Area -->
            <div class="header-menu-area">
                <div class="container">
                    <nav class="navbar navbar-expand-lg navbar-urbanhouse">
                        <a href="{{route('index')}}"><img src={{$general->logo}} style="width: 160px;"></a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarNav">
                            <ul class="navbar-nav">
                                <li class="nav-item @if(Request::is('/')) active  @endif">
                                    <a class="nav-link" href="{{route('index')}}">Home <span class="sr-only">(current)</span></a>
                                </li>
                                <li class="nav-item @if(Request::is('*about*')) active  @endif " >
                                    <a class="nav-link" href="{{route('about')}}" >About Us</a>
                                </li>
                                <li class="nav-item @if(Request::is('*services*')) active  @endif">
                                    <a class="nav-link" href="{{route('services')}}" >Our Services</a>
                                </li>
                                  <li class="nav-item @if(Request::is('*suppliers*')) active  @endif">
                                    <a class="nav-link" href=" {{route('suppliers')}}" >Our Supplies</a>
                                </li>
                                <li class="nav-item @if(Request::is('*contact*')) active  @endif">
                                    <a class="nav-link" href="{{route('contact')}}">Contact Us</a>
                                </li>
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
            <!-- END Header Menu Area -->
        </header>
        <!-- Header END -->
        



        @yield('content')


        <!-- START Footer Area  -->
        <footer>
            <div id="footer-widget-area">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-4 col-md-6">
                            <div class="footer-widget widget_text">
                                <a href="index.html"><img src={{asset("assets/images/logos/logo-footer.svg")}} style="width: 250px;"></a>
<!--                                <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehENDerit.</p>-->
                            </div>
                            
                        </div>
                        <div class="col-lg-2 col-md-6">
                            <div class="footer-widget widget_custom_menu">
                                <h3 class="footer-widget-title">Social Media</h3>
                                <div class="footer-widget widget_social">
                                <ul>
                                    <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                                    <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                                    <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
                                </ul>
                            </div>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6">
                            <div class="footer-widget widget_custom_menu">
                                <h3 class="footer-widget-title">Main Pages</h3>
                                <ul>
                                    <li><a href="index.html">Home</a></li>
                                    <li><a href="about.html">About Us</a></li>
                                    <li><a href="services.html">Our Services</a></li>
                                    <li><a href="contact.html">Contact Us</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6">
                            <div class="footer-widget widget_text">
                                <h3 class="footer-widget-title">Get in Touch</h3>
                                <div class="footer-icon-text">
                                    <div class="footer-icon"><i class="fa fa-map-marker" aria-hidden="true"></i></div>
                                    <div class="footer-icon-info">
                                        <p>Turkey / MERSİN </p>
                                        <p>GAZİ MAH.</p>
                                    </div>
                                </div>
                                <div class="footer-icon-text">
                                    <div class="footer-icon"><i class="fa fa-phone" aria-hidden="true"></i></div>
                                    <div class="footer-icon-info">
                                        <p>+90 534 078 13 62</p>
                                    </div>
                                </div>
                                <div class="footer-icon-text">
                                    <div class="footer-icon"><i class="fa fa-clock-o" aria-hidden="true"></i></div>
                                    <div class="footer-icon-info">
                                        <p>Mon - Fri: 08.00 - 17.00</p>
                                    </div>
                                </div>
                                <div class="footer-single-link"><a href="#"><span><i class="fa fa-angle-right" aria-hidden="true"></i></span> Contact Us</a></div>
                            
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div id="footer-copyright-area">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-6 col-md-12">
                            <p>&copy; Copyright 2021 Oilfield Support, All Rights Reserved</p>
                        </div>
                        <div class="col-lg-6 col-md-12">
                            <nav>
                                <ul style="  justify-content: flex-end;">
                                    
                                    <li><a href="#">Privacy Policy</a></li>
                                    <li><a href="#">Terms of Service</a></li>
                               
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- END Footer Area  -->
        <!-- jQuery 3.2.1 js -->
        <script src={{asset("assets/js/vendor/jquery-3.2.1.slim.min.js")}}></script>
        <!-- Bootstrap 4 Beta depENDency popper 1.11.0 js  -->
        <script src={{asset("assets/js/vendor/popper.min.js")}}></script>
        <!-- Bootstrap 4 Beta JS -->
        <script src={{asset("assets/js/vendor/bootstrap.min.js")}}></script>
        <!-- WoW v-1.3.0 JS -->
        <script src={{asset("assets/js/vendor/wow-1.3.0.min.js")}}></script>
        <!-- Owl Carousel JS -->
        <script src={{asset("assets/js/vendor/owl.carousel.min.js")}}></script>
        <!-- Waypoint Js -->
        <script src={{asset("assets/js/vendor/waypoint/noframework.waypoints.min.js")}}></script>
        <!-- CountUp Js -->
        <script src={{asset("assets/js/vendor/countUp.min.js")}}></script>
        <!-- Isotope js for filter content js -->
        <script src={{asset("assets/js/vendor/isotope.js")}}></script>
        <!-- Magnific Popup - v1.1.0 js -->
        <script src={{asset("assets/js/vendor/jquery.magnific-popup.min.js")}}></script>
        <!-- Image Loaded Packeg -->
        <script src={{asset("assets/js/vendor/imagesloaded.pkgd.js")}}></script>
        <!-- Template JS -->
        <script src={{asset("assets/js/main.js")}}></script>

        <script>
            //console.log($('.uh-home-slider').children());
            var x=1;
            // $('#as').children().each(function(){
            //     $(this).prop('id', 'slide-'+x);
              
            //     if(true)
            //     {
            //         $(this).css({
            //         "background-size": "cover",
            //         "background-position": "center",
            //         "background-image":url('/assets/images/slider-banner/slider-x.jpg')
            //         });
            //     }
            //     x++;
            // });

            //console.log($('.uh-home-slider').find('.reals'));
            $('.uh-home-slider').find('.item').each(function(){
                $(this).prop('id', 'slide-'+x);
               // console.log($(this).text(),x);
                if(true )
                {
                    //console.log($(this).attr('name'));
                    $(this).css({
                    "background-size": "cover",
                    "background-position": "center",
                    //"background-image":"url(/assets/images/slider-banner/slider-"+x+".jpg)"
                    "background-image":"url("+$(this).attr('name')+")"
                    });
                }
                x++;
            });
            var i;
            //var as=$('.uh-home-slider').find('.item');
            //console.log(as);
            //for(i=0;i<as.length;i++){
               // console.log(as[i].find('.item'));
                //as[i].style.backgroundSize="cover";
                //as[i].style.backgroundPosition="center";
                //as[i].style.backgroundImage=`url('/assets/images/slider-banner/slider-x.jpg')`;
                // ({
                //         "background-size": "cover",
                //         "background-position": "center",
                //         "background-image":`url('/assets/images/slider-banner/slider-x.jpg')`
                //         });
           // }



           // $('element').attr('id', 'value');

        </script>
    </body>
</html>